[package]
name = "contact_book"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dialoguer = "0.11.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
